--- #YAML:1.0
name:                OpenCA-DBI
version:             2.0.45
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBI:                           1.19
    OpenCA::CRL:                   0.9
    OpenCA::OpenSSL:               0.9
    OpenCA::REQ:                   0.9
    OpenCA::Tools:                 0.4
    OpenCA::X509:                  0.9
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
